#Application name
spring.application.name=payment-platform

# Server port
server.port=8080

# ===============================
# PostgreSQL Database
# ===============================

spring.datasource.url=jdbc:postgresql://localhost:5432/payment_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===============================
# Actuator
# ===============================
management.endpoints.web.exposure.include=health,info

# ==========================================
# Redis
# ==========================================

spring.data.redis.host=localhost
spring.data.redis.port=6379

#Spring Security OAuth2 Resource Server Configuration
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=